version: "3.4"
services:
  keybase-bot:
    build:
      context: .
      network: host
    environment:
      - KB_USERNAME=${KB_USERNAME}
      - KB_PAPERKEY=${KB_PAPERKEY}
      - KB_TEAM_NAME=${KB_TEAM_NAME}
      - KB_RESERVE_CHANNEL=${KB_RESERVE_CHANNEL}
      - KB_POST_CHANNEL=${KB_POST_CHANNEL}
      - PAST_WEEK_LIMIT=${PAST_WEEK_LIMIT}
      - DATA_FILE=/app/fnb_bot_storage/data.json
      - COMMAND_PREFIX=!reservation-bot
      - ANNOUNCEMENT_CRON=${ANNOUNCEMENT_CRON}
      - PURGE_CRON=${PURGE_CRON}
    volumes:
      - ../fnb_bot_storage:/app/fnb_bot_storage